### ISSUE TITLE
Enhance detecting code for iOS8 and over

### ISSUE THREAD

**Issue by sculove** [hammerjs/hammer-time#17]
https://github.com/hammerjs/hammer-time/blob/master/hammer-time.js#L34-L42
Is this a detecting code for iOS8 and over ?

Why don't you change code using indexedDB? 
http://caniuse.com/#search=indexedDB

Although iOS8,9 had a seriously bug, we can reduce code.

**Comment by arschmitz** [comment]
It is for that precisely. I know indexedDB does not work in iOS8 webviews so i'm not sure if this will work. Can you confirm if a feature detect for indexedDB shows support or not in an iOS 8 webview?

**Comment by sculove** [comment]
I check following code.

```
"indexedDB" in window
```

iOS7 webview returns 'false'.
iOS8 webview returns 'true'.
Unfortunately, iOS9 webview returns 'false'

**Comment by arschmitz** [comment]
Ok so it sounds like that wont work for detecting iOS8+ which is the intention

**Comment by sculove** [comment]
OK. I'll try to look for more different methods.

**Comment by arschmitz** [comment]
@sculove sounds good when i added this it was the best one i found but certainly open to improve.

**Comment by sculove** [comment]
I seem to find a different method. #18

**Comment by arschmitz** [comment]
merged pr
