### ISSUE TITLE
dist/hammer-time.min.js contains `hasTouchNone` which results in error 

### ISSUE THREAD

**Issue by ArthurClemens** [hammerjs/hammer-time#21]

**Comment by tomekmarchi** [comment]
Can second this notion. I have added if(!this.hasTouchNone){return;} to the sections that call it in the code.
`!function(){void 0!==document.documentElement.style["touch-action"],window.Hammer=window.Hammer||{};var a=window.MutationObserver||window.WebKitMutationObserver,b=/touch-action[:][\s]*none[^;'"]*/,c=/touch-action/,d=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?!0:!1,e=function(){try{var a=document.createElement("canvas");return!(!window.WebGLRenderingContext||!a.getContext("webgl")&&!a.getContext("experimental-webgl"))}catch(b){return!1}}(),f=e&&d;window.Hammer.time={getTouchAction:function(a){return this.checkStyleString(a.getAttribute("style"))},checkStyleString:function(a){return c.test(a)?b.test(a)?"none":!0:void 0},touchHandler:function(a){if(!this.hasTouchNone){return;}if(this.hasTouchNone(a.target)&&(!f||Date.now()-a.target.lastStart<125)){if("touchend"===a.type){var b=new MouseEvent("click",{view:window,bubbles:!0,cancelable:!0});setTimeout(function(){a.target.dispatchEvent(b)},0)}a.preventDefault()}delete a.target.lastStart},styleWatcher:function(a){a.forEach(this.styleUpdater,this)},styleUpdater:function(a){if(a.target.updateNext)return void(a.target.updateNext=!1);var b=this.getTouchAction(a.target);return b?void("none"!==b&&(a.target.hadTouchNone=!1)):void(!b&&(a.oldValue&&this.checkStyleString(a.oldValue)||a.target.hadTouchNone)&&(a.target.hadTouchNone=!0,a.target.updateNext=!1,a.target.setAttribute("style",a.target.getAttribute("style")+" touch-action: none;")))},install:function(){document.addEventListener("touchend",this.touchHandler.bind(this),!0),document.addEventListener("mouseup",this.touchHandler.bind(this),!0),f&&document.addEventListener("touchstart",function(a){if(!this.hasTouchNone){return;}this.hasTouchNone(a.target)&&(a.target.lastStart=Date.now())}.bind(this)),this.observer=new a(this.styleWatcher.bind(this)).observe(document,{subtree:!0,attributes:!0,attributeOldValue:!0,attributeFilter:["style"]})}},window.Hammer.time.install()}();
`

**Comment by mrsubtle** [comment]
Here too.  Same stack as @tomekmarchi

**Comment by arschmitz** [comment]
this should be fixed on master the minified file was out of date. Please comment if you have any additional trouble.
