### ISSUE TITLE
A new release is in order 

### ISSUE THREAD

**Issue by kiwiupover** [hammerjs/hammer-time#24]
We ran into issues in our test when moving from fastclick to hammertime. It seems to me that PhantomJS 2.1.1 is returned as a touched device. 

It looks like the issue is fixed but unreleased. 
### master:

https://github.com/hammerjs/hammer-time/blob/master/hammer-time.js#L73-L79
### verision 1.0.0

https://github.com/hammerjs/hammer-time/blob/v1.0.0/hammer-time.js#L68-L70

**Comment by arschmitz** [comment]
@kiwiupover no problem that change was actually just code cleanup was unaware of that issue

**Comment by arschmitz** [comment]
done

**Comment by kiwiupover** [comment]
Thanks heaps
