### ISSUE TITLE
hadTouchNone

### ISSUE THREAD

**Issue by joelcoxokc** [hammerjs/hammer-time#25]
FYI The version with the undefined function `hadTouchNone` is still the downloadable version on your website!

**Comment by ekryski** [comment]
:+1: ran into this as well

**Comment by roblav96** [comment]
Agreed. Totally throwing me off. lol

**Comment by gamecubate** [comment]
+1

**Comment by arschmitz** [comment]
the issue with the website is fixed

**Comment by ekryski** [comment]
@arschmitz woop woop!
