### ISSUE TITLE
[question] replacement of fastclick.js??

### ISSUE THREAD

**Issue by siddo420** [hammerjs/hammer-time#27]
I am not an experienced front end developer, so wanted to confirm that hammer-time is a replacement for fastclick.js.

I was confused b/c fastclick is almost 6 times bigger than hammer-time.

**Comment by arschmitz** [comment]
Yes hammer time is a replacement for fastclick.js but they work very very differently. Hammer time does it by polyfilling touch-action css while fastclick.js uses its own algorithm.

And yes yes hammer time is much much smaller.
