### ISSUE TITLE
Code should exit if MutationObserver isn't supported.

### ISSUE THREAD

**Issue by bryanbraun** [hammerjs/hammer-time#7]
The polyfill relies on MutationObserver which [isn't supported in several environments](http://caniuse.com/#feat=mutationobserver) (like old IE). That's not a big deal since those environments don't typically have the 300ms delay, **but** we need to exit early if the MutationObserver isn't supported or else we'll get errors in those environments. For example:

IE 9:
![image](https://cloud.githubusercontent.com/assets/1256329/10920944/db665352-8240-11e5-8145-4d0265340a69.png)

PhantomJS 1.9.8:
![image](https://cloud.githubusercontent.com/assets/1256329/10920904/aae1a4ca-8240-11e5-8d2b-91f9d527168a.png)

**Comment by arschmitz** [comment]
@bryanbraun good catch thank you will get this fixed and thank you for the other 2 patches!
